[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "~2.1"
solana-client = "~2.1"
solana-account-decoder = "~2.1"
