[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-account-decoder = "3"
solana-client = "3"
solana-instruction = "3"
solana-pubkey = "3"
