[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]

solana-client = { version = "3.1.1" }
solana-account-decoder = "3.1.1"

solana-sdk = { version = "3.0.0" }